### ISSUE TITLE
bouncycastle crypto ands injector

### ISSUE THREAD

**Issue by clover73** [christianspecht/scm-backup#65]
what is bouncy house crypto and simple injector or mail kit and why are they in the release but not here

**Comment by christianspecht** [comment]
MailKit (for sending emails) and SimpleInjector (DI Container) are libraries that SCM Backup uses internally.

The libraries are not directly committed to the repository because they are referenced as NuGet packages [here](https://github.com/christianspecht/scm-backup/blob/6090ea951f806bedc43643700b9cf950e9664bd8/src/ScmBackup/ScmBackup.csproj#L29) and [here](https://github.com/christianspecht/scm-backup/blob/6090ea951f806bedc43643700b9cf950e9664bd8/src/ScmBackup/ScmBackup.csproj#L33).

BouncyCastle is not directly referenced in the project, but I'm 100% sure that it's a dependency of MailKit, that‘s why it‘s in the release as well.
