### ISSUE TITLE
Misleading warning backing up a seperate workspace in bitbucket

### ISSUE THREAD

**Issue by exptom** [christianspecht/scm-backup#68]
My bitbucket account has access to a number of workspaces. I followed the docs that state:

> 
> By default, a user’s workspace ID is equal to the user name, but it’s possible to [change the workspace ID](https://confluence.atlassian.com/bitbucket/change-a-workspace-id-966686598.html), so workspace ID and user name don’t match anymore.
> 
> In this case, you need to set name to the workspace ID and authName to the user name.

and this works well.

However this warning is shown:
> <title>: AuthName and Name must be equal for hoster bitbucket. If they are different, SCM Backup will backup public repositories only!

This is untrue as all the repos in the workspace are private and they have been backed up.

**Comment by christianspecht** [comment]
Makes sense.  
However, I didn't use Bitbucket that much since they replaced teams by workspaces, so I'm not sure if the solution I have in mind is the best one.

---

Here are my thoughts:

1. [This section on the same page](https://docs.scm-backup.org/en/latest/config-bitbucket.html#sources) in the docs also states:

    > The `type` property of the source doesn't matter anymore *(because for what SCM Backup does, there's no difference between users and workspaces)*, so SCM Backup will accept either `user` or `org`

2. The misleading warning [is generated here](https://github.com/christianspecht/scm-backup/blob/6090ea951f806bedc43643700b9cf950e9664bd8/src/ScmBackup/Hosters/ConfigSourceValidatorBase.cs#L56), and the whole check is only done if the `type` of the source is not `org`.

3. If your user has access to multiple workspaces, they are probably more like the previous "teams" (and not your user's "personal" workspace).  

**So IMO this is more of a documentation issue - I should probably replace the "The `type` property of the source doesn't matter anymore..." section by an explanation that you need to set the `type` of the source to `org` if the workspace is not your user's personal workspace.  
Do you agree?**
