### ISSUE TITLE
Can't get it to do anything

### ISSUE THREAD

**Issue by dragonstar0828** [christianspecht/scm-backup#70]
Trying to back up some repositories from BitBucket.
 
Set up a minimal .yml file with my user name and tried both my account password and the company app password.
 
Launch the app and nothing happens - no interface, no error messages, no log file in the back up folder - nothing.
 
What am I missing?
 
Thanks in advance for any help.
 
drc  :)

**Comment by christianspecht** [comment]
1. To see if SCM Backup runs on your machine at all, start it with the config file that was included in the download.  
  This should backup the public repos of [this user](https://github.com/scm-backup-testuser/)

2. If step 1 didn't work either, tell me more about your machine: operating system? Correct .NET Core version installed? --> https://docs.scm-backup.org/en/latest/install.html#system-requirements

3. If step 1 *did* work, can you share the settings file that you created for Bitbucket? You can replace usernames, passwords etc. by `xyz...`, of course. I just want to see the file structure.

**Comment by dragonstar0828** [comment]
Nothing happened when I used the original .yml file.
 
I probably don't have the right .net Core installed but I have no idea which file to dl form the download page - SDK, ASP.net runtime, .net desktop runtime, .net runtime for version 3.1.28...
 
... OR down I need to go to the bottom of the page and get original 3.1.0?
 
 
drc   :)

**Comment by christianspecht** [comment]
Okay, I see that the download page has changed since I last edited the "system requirements" page in the docs. Last time I checked, there weren't that many different downloads.

- SCM Backup is a console app, so the .NET runtime ("contains just the components needed to run a console app") *should* be enough.  
- You don't need specifically 3.1.**0**, any 3.1.x should work. The machine where I'm writing this right now has 3.1.16 installed.

**Comment by dragonstar0828** [comment]
Good morning.
 
Should I install the x64 or x86 version?

**Comment by christianspecht** [comment]
I think Microsoft's general advice is to install x64 when you have a x64 operating system.

---

By the way, how did you launch the app? Double-click on the .exe in Windows Explorer (I suppose you're on Windows?)

SCM Backup is a command-line app. If you start it by double-clicking it in the Explorer and something goes wrong (e.g. it crashes because .NET is not installed), there's probably some kind of error message shown on the command line, but you don't see it because the window closes immediately.
Try opening the command-line of your choice and start SCM Backup there.

**Comment by dragonstar0828** [comment]
Tried it from the command line and got the error...
 
A fatal error occurred. The required library hostfxr.dll could not be found.
 
 I'll try and find time today to install the net core stuff and try it again.
 
 
drc  :)

**Comment by dragonstar0828** [comment]
Looks like it's working for the provided .yml file.
 
I'll have to recreate the one I had done for the company repositories and see if I can get that working.
 
 drc  :)

**Comment by christianspecht** [comment]
OK, closing this for now. If you can't get the yml file for the company repos working, feel free to open this again.

**Comment by dragonstar0828** [comment]
Well I finally got it configured and running.
 
However of the 50+ repositories we have it seems to have only processed 9 of them, created a back up folder for the 10th one, and just stopped moving - as in nothing on the screen and the folder for the 10th repository is empty and it's been running almost an hour.
 
Thoughts?
 
drc  :)

**Comment by dragonstar0828** [comment]
NEVER MIND - sorted it out and got my first full back up done.  Woo hoo!
 
 drc  :)

**Comment by christianspecht** [comment]
Nice ;-)

Why didn’t it work the first time?
Was it anything that I could improve in the docs?

**Comment by dragonstar0828** [comment]
I noticed the repo it seemed stuck on contained an .exe file about 9mb in size.
 
While not a big file for today's file transfer speeds in my opinion, after I deleted it from the repo and re-ran it this time it zipped right through that repo and finished all the remaining ones after it.
 
 
drc  :)
