### ISSUE TITLE
Add option to compress repository after download

### ISSUE THREAD

**Issue by robpinheiro** [christianspecht/scm-backup#71]
Hello,
I would like to know if it would be possible to implement the option to compress the repository after downloading.
Thanks.

**Comment by christianspecht** [comment]
I suppose by "compressing" you mean creating a .zip file or something like that?  
If yes, IMO it doesn't make sense.

It wouldn't be much effort to zip each repository after downloading, but the next time SCM Backup runs, it would have to unzip it again, in order to pull/fetch again with Git....and then zip it again. That would significantly increase the time one SCM Backup run takes...the larger your repositories are, the longer it will take.

Plus, Git repositories seem to be pretty compressed anyway. I'm using SCM Backup to backup my GitHub account including the SCM Backup repository.
I just tried to compress the backed up repository with 7-Zip:

- Uncompressed repository: 756 KB
- .zip file (max. possible compression): 754 KB
- .7z file (max. possible compression): 632 KB

So IMO it's not worth the effort to save a few kilobytes.
